services:

  mysql:
    image: mysql:8
    container_name: ${DATABASE_URL}
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASS}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASS}
    ports:
      - 33065:${DATABASE_PORT} # Mapea el puerto MySQL al host (opcional)
    volumes:
      - db_data:/var/lib/mysql # Volumen persistente para datos de MySQL
    networks:
      - app-network

  bingoweb:
    image: djavic/bingoweb:latest
    container_name: bingo-web
    ports:
      - "${API_HTTP_PORT}:${API_HTTP_PORT}" # Mapea el puerto del backend al host
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASS=${DATABASE_PASS}
      - DATABASE_PORT=${DATABASE_PORT}
      - API_HTTP_PORT=${API_HTTP_PORT}
      - SSL_CONFIG_KEY=./certs/server.key
      - SSL_CONFIG_CERT=./certs/server.cert
    volumes:
      - extension_files:/app/Backend/uploads/extensions # Volumen persistente para extensiones
    depends_on:
      - mysql
    networks:
      - app-network
    entrypoint: >
      /bin/sh -c " echo 'Esperando 15 segundos para que la base de datos esté lista...'; sleep 15; node app.js;"

volumes:
  db_data:
  extension_files:


networks:
  app-network:
